name: Deploy Static Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

#      - name: Set up Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable

#      - name: Install Marmite
#        run: cargo install marmite

      - name: Download Marmite binary
        run: |
          MARMITE_VERSION=$(curl -s https://api.github.com/repos/rochacbruno/marmite/releases/latest | jq -r .tag_name)
          curl -L -o marmite.tar.gz "https://github.com/rochacbruno/marmite/releases/download/${MARMITE_VERSION}/marmite-${MARMITE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xzf marmite.tar.gz
          chmod +x marmite

      - name: Build the site with Marmite
        run: ./marmite . site -v
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
